trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'MPII']
testset: 'PW3D'

lr_dec_epoch: [10]
end_epoch: 11
# lr_dec_epoch: [18, 25]
# end_epoch: 30
lr: 0.001
lr_backbone: 0.0001
lr_dec_factor: 10

train_batch_size: 192
test_batch_size: 1024